version: '3.7'

services:

  nginx:
    image: nginx:1.17-alpine
    container_name: topshiriq-nginx
    restart: unless-stopped
    working_dir: /app
    ports:
      - 20080:80 # frontend
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - db
    networks:
      - topshiriq

  php-fpm:
    build: docker/php-fpm
    restart: unless-stopped
    container_name: topshiriq-php
    working_dir: /app
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db
    networks:
      - topshiriq

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: topshiriq
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    networks:
      - topshiriq


networks:
  topshiriq:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.227.0/28
